const { GoogleGenAI } = require("@google/genai");

const puppeteer = require("puppeteer");
const fs = require("fs");
const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const executablePath = await puppeteer.executablePath();

console.log("Executable path:", executablePath);
console.log("Exists:", fs.existsSync(executablePath));

async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `
You are an expert technical interviewer and career coach.

Analyze the following candidate information.

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}

Return ONLY valid JSON.

Do NOT wrap the response in markdown.
Do NOT add explanations.
Do NOT add any extra fields.
Do NOT use snake_case.
Use exactly the field names below.

The JSON must exactly match this structure:

{
  "matchScore": 85,
  "technicalQuestions": [
    {
      "question": "",
      "intention": "",
      "answer": ""
    }
  ],
  "behavioralQuestions": [
    {
      "question": "",
      "intention": "",
      "answer": ""
    }
  ],
  "skillGaps": [
    {
      "skill": "",
      "severity": "low"
    }
  ],
  "preparationPlan": [
    {
      "day": 1,
      "focus": "",
      "tasks": [
        ""
      ]
    }
  ],
  "title": ""
}

Rules:

- matchScore must be between 0 and 100.
- title must contain the exact job title.
- Return exactly 6 technicalQuestions.
- Return exactly 6 behavioralQuestions.
- Return exactly 6 preparationPlan entries (Day 1 through Day 6).
- Every technical question MUST contain:
  - question
  - intention
  - answer
- Every behavioral question MUST contain:
  - question
  - intention
  - answer
- Every skill gap MUST contain:
  - skill
  - severity (only "low", "medium", or "high")
- Every preparation plan entry MUST contain:
  - day
  - focus
  - tasks (array of strings)
`;

  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash-lite",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
    },
  });

  const text = response.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error("AI did not return any content.");
  }

  let report;

  try {
    report = JSON.parse(text);
  } catch (err) {
    console.error("Invalid JSON returned by AI:");
    console.error(text);
    throw new Error("AI returned invalid JSON.");
  }

  return report;
}

async function generatePdfFromHtml(htmlContent) {
  console.log("Starting PDF generation");
  const executablePath = await puppeteer.executablePath();
  console.log("Executable path:", executablePath);
  const browser = await puppeteer.launch({
    executablePath,
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });
  console.log("Browser launched");
  const page = await browser.newPage();
  console.log("Page created");
  await page.setContent(htmlContent, { waitUntil: "networkidle0" });
  console.log("HTML loaded");

  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: {
      top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm",
    },
  });
  console.log("PDF created");
  await browser.close();

  return pdfBuffer;
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  try {
    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                        Return ONLY valid JSON.

{
  "html": "<complete HTML document>"
}

Do not wrap the JSON in markdown.
Do not add explanations.
                    `;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash-lite",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const text = response.candidates[0].content.parts[0].text;
    const jsonContent = JSON.parse(text);

    const pdfBuffer = await generatePdfFromHtml(jsonContent.html);

    return pdfBuffer;
  } catch (err) {
    console.error("generateResumePdf failed:");
    console.error(err);
    throw err;
  }
}

module.exports = { generateInterviewReport, generateResumePdf };
